// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wine_Shop_Balkaran.Data;

namespace Wine_Shop_Balkaran.Migrations
{
    [DbContext(typeof(Wine_Shop_Balkaran_DbContext))]
    partial class Wine_Shop_Balkaran_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wine_Shop_Balkaran.Bussiness.CustomerMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RateListMasterID")
                        .HasColumnType("int");

                    b.Property<int?>("WineMasterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RateListMasterID");

                    b.HasIndex("WineMasterID");

                    b.ToTable("CustomerMasters");
                });

            modelBuilder.Entity("Wine_Shop_Balkaran.Bussiness.RateListMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("RateListMasters");
                });

            modelBuilder.Entity("Wine_Shop_Balkaran.Bussiness.WineMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("WineMasters");
                });

            modelBuilder.Entity("Wine_Shop_Balkaran.Bussiness.CustomerMaster", b =>
                {
                    b.HasOne("Wine_Shop_Balkaran.Bussiness.RateListMaster", "RateListMaster")
                        .WithMany("CustomerMasters")
                        .HasForeignKey("RateListMasterID");

                    b.HasOne("Wine_Shop_Balkaran.Bussiness.WineMaster", "WineMaster")
                        .WithMany("CustomerMasters")
                        .HasForeignKey("WineMasterID");
                });
#pragma warning restore 612, 618
        }
    }
}
